general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

# this is a color override for tokionight omarchy theme so it matches nvim onedark theme
[colors]
[colors.primary]
background = '#2c2d30'

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 11

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
